### ISSUE TITLE
git workflow

### ISSUE THREAD

**Issue by reverland** [HalfdogStudio/coco-blog#1]
面试官面试的时候，经常会问一个问题，你有团队协作开发的经验吗？我想其中一个含义就是说是否使用过协作工具吧，对于codemonkey们来说，最流行的协作工具就是git吧
## 基本流程

在工作中，我们在master分支中保留稳定的功能，每次需要开发新功能、修复bug的时候，都会新开一个分支进行操作

```
git checkout -b bug-1
```

在我们做了一个“元修改”后，可以看看自己做了哪些修改。

```
git diff
```

确定没什么问题之后添加这些修改

```
git add new_file
git add -p file_changed
```

再次检查，并添加commit信息

```
git commit
```

接着我们会把做了修改的分支push到git服务器上

```
git push origin bug-1
```

一般我们会发一个合并到master分支的merge request，但在github上，可能Pull request 更合适。pull request之后会at合适的人review这个request。review的人觉得没什么问题，就给merge到master中
## 修正冲突

但有时候你发现你发PR的时候你的分支和master已经有冲突了。

发起merge request的人需要检查自己的分支，可能在自己做修改的时候，master已经变化了

这时候可以把master新增加的commit rebase到自己做修改的分支上。

```
git pull origin master --rebase
```

如果有冲突，修正它，再commit
## 其它

有时候你一连commit好几次，但是都只是一个特性，想把commit合并。

```
git rebase -i HEAD~3
```

以上命令会把最后三个commit都列出来让你操作，pick第一个，squash剩下两个，就能合并。当然还能做些其它操作比如修改commit信息，按提示操作就行。

当你只是想修改最近一次commit信息，比如commit信息打错字了，

```
git commit --amend
```

有时候，你只想把某个分支一个commit给合并到当前分支，这时候可以使用cherry-pick。

```
git cherry-pick [hash]
```

hash是那个commit对应的哈希，通过git log命令可以查看。

如果有时错误添加了文件，比如想ignore的文件，在.gitignore添加这个文件，然后

```
git rm this_file --cached
```

在git记录中把该文件删除
## First Blood

@xiaoxiaff 我常用的就上面那些，你来该项目一血。

我们准备做的东西是一个使用vuejs、webpack的前端项目，那么

首先，准备好基本环境
1. 安装nodejs
2. 安装[n](https://github.com/tj/n)
3. n latest 
4. 安装[vue-cli](https://github.com/vuejs/vue-cli)
5. 根据vue-cli说明，使用webpack template，搭好项目脚手架：`vue init webpack coco-blog`
6. 将给项目作为一个已有项目上传

**Comment by reverland** [comment]
Abort Vue.js

https://github.com/blake-newman/vue-progressive-enhancement-workshop/blob/master/assets/Vue_Progressive-enhancement-workshop.pdf

**Comment by reverland** [comment]
@xiaoxiaff 在git commit message中可以包含

```
fix #1
```

so that this issue will be closed automaticly

**Comment by d0u9** [comment]
经常用到的一个`rm -fr ./* && git reset --hard HEAD`...

**Comment by reverland** [comment]
@d0u9 。。。。。。大神你在干什么

**Comment by d0u9** [comment]
@reverland  学习C++。。。 古老的语言。。

**Comment by d0u9** [comment]
@reverland  学习C++。。。 古老的语言。。
手一抖点错了。。。
