### ISSUE TITLE
关于 vue webpack template

### ISSUE THREAD

**Issue by reverland** [HalfdogStudio/coco-blog#2]
ps:我讲的不是真理

我们的项目用vue-template框架快速搭建了脚手架。可以看到，围绕webpack的大量配置和该模板推荐的基本代码组织结构。

然而暂时先不用管这些，首先，看看我们使用的东西。
## Vue.js

首先这是一个[Vue](http://vuejs.org/)的项目。
### MVVM

首先从MVVM开始说，MVVM即[model-view-viewmodel](https://msdn.microsoft.com/en-us/library/hh848246.aspx)。model层代表原始数据，view表示UI视图，viewmodel则表示中间层。这样做是为了将业务逻辑和原始数据-展示数据和UI逻辑-UI进行解耦。

这一切理论的出现，都源于浏览器性能的不断提升，业务需求不断复杂化。

Vue作为一个Viewmodel层解决方案，负责几件事：
1. 将展示数据和UI绑定，如果展示数据发生变化，通知UI
2. 接受来自原始数据的变化，更新展示数据
3. 当UI操作改变展示数据时，通知model层。

跟大多MV*M框架类似，Vue实现了以下两个核心功能完成viewmodel和view的绑定
1. 扫描html模板，根据其中的数据绑定生成更新UI函数
2. 更改初始数据的getter和setter（在读写数据时的钩子函数），这样就能在设置数据时搜集依赖（内外部数据依赖关系）和执行更新UI函数。
### 单文件vue组件

在`src`中，我们可以看到`App.vue`和`components/Hello.vue`.

一般我们直接书写单文件vue组件，但这不是使用vue.js的唯一方法！只是其中一种可能。非常推荐的一种可能。

webpack使这可能成为现实。

Web平台，最早为“网页”而生，而不是UI或应用而生，有两个问题
1. 缺乏广泛支持的解耦方案。
2. 原生仅仅支持css、javascript、html

将所有功能都写到一个html页面中，所有引入的js文件都在一个全局作用域中，所有css规则以一种奇怪的方式层叠着，各种异步处理穿插业务逻辑流程。整个结果就是，非常难以编写可维护的前端代码。

不信可以随便找找较大网站的前端代码，看看他们的js代码有多长、有多少状态、多少事件等等

手工维护复杂代码的结果就是混乱、无法维护、和充满bug的前端代码。

为了解决这些问题，web components标准应运而生，你现在看到的原生播放器，实际上就是隔离的web组件。然而，并不是所有浏览器都有很好且一致的web components实现。

通过.vue形式的单文件组件方式，你可以书写web components风格的组件。组件内的样式、逻辑、UI与外界隔离。

在组件中，可以定义html模板，样式。更重要的是，数据、方法、生命周期函数。所有这些都封装为一个JS模块，而这一切都由webpack完成，它会解析你用到的外界资源（就是依赖）并通通打包成浏览器可以识别的javascript、css、html、图片等等。
## 接下来

熟悉
- vue-loader文档
- webpack文档
- vue.js文档
- ~~vue-router文档~~

其它可能有用的东西
- ES6语法
- less语法

**Comment by reverland** [comment]
一个博客的主页可能分逻辑相互隔离的三部分。他们在样式上可能也有隔离或公共的部分
- nav
- content
- footer

@xiaoxiaff  先熟悉一下框架吧

请新开一个vue-practice的分支，试参考http://blog-next.reverland.org 实现博客主页，实现三个组件。暂时不考虑链接，可不使用UI框架。

**Comment by xiaoxiaff** [comment]
vue.js算是一个服务器框架吗？还是只处理前端的框架？
安装完后登陆显示的是vue的界面，所以vue可以理解为一个服务器框架？但是为什么看到的东西都是前端和数据的交互绑定，很少看到服务器后台的一些操作，vue-router算是服务器路由操作吧，但是中间件之类的呢，都是通过模块提供的？
webpack可以理解为模块化打包工具，将js，css甚至vue当做模块进行打包？感觉似乎不难但是看文档啥的感觉内容好多好杂。

**Comment by reverland** [comment]
vue只是一个前端viewmodel框架，本项目所有东西都不关后台的事情。这是纯粹的前端项目，甚至缺少一般前端项目和后端交互的部分。

vue-router是在前端模拟路由逻辑，谁也没说过路由逻辑一定要服务器来做。前端接管路由逻辑可以维持路由之间的状态，这为复杂应用的实现打下了基础。

一般，现代前后端解耦与分离很彻底。前端项目和后端项目通过API请求（比如纯粹的AJAX）相互通信，前后端可以并行开发，而不是前端还得参与到后端视图模板的开发中去。

webpack的文档是出名的复杂，因为，打包需求是多种多样的...webpack有很多黑魔法特性。
